name: CI

on:
  push:
    branches: [main]
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  checks: write

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - uses: VirtusLab/scala-cli-setup@v1.5
        with:
          scala-cli-version: 1.8.4
      - uses: actions/setup-java@v5
        with:
          distribution: zulu
          java-version: 21
      - uses: coursier/cache-action@v7
      - name: Set Homebrew env
        shell: bash
        run: echo "HOMEBREW_NO_SANDBOX_LINUX=1" >> $GITHUB_ENV
      - name: Set up Homebrew
        uses: Homebrew/actions/setup-homebrew@main
      - name: Install deder
        run: brew install sake92/tap/deder
      - name: Run tests
        shell: bash -eo pipefail {0}
        run: |
          deder exec -t test -m core-test -m parser-semanticdb-test -m parser-jdeps-test -m cli-test
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v6
        if: success() || failure()
        with:
          report_paths: '.deder/out/**/reports/junit/TEST-*.xml'
